import EcologyBehavioralEcologyCanonicalLaneLean.AdmissibleClass

namespace HautevilleHouse
namespace EcologyBehavioralEcologyCanonicalLaneLean

end EcologyBehavioralEcologyCanonicalLaneLean
end HautevilleHouse